server:
  port: 8086
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.102.128.140:3306/tally?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: PassWord1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  freemarker:
    suffix: .ftl
  redis:
    host: 127.0.0.1
    port: 6379
    database: 5
    timeout: 300
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl